---
- name: Download Tomcat from tomcat.apache.org
  hosts: [all,localhost]
  become: true

  tasks:
    - name: Create a directory /opt/tomcat/
      file: 
        path: /opt/tomcat
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Download tomcat
      get_url:
          url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.43/bin/apache-tomcat-10.1.43.tar.gz
          dest: /opt/tomcat
          mode: 0755
          owner: ubuntu
          group: ubuntu  

